### PR TITLE
Adding some config utils while trying to understand the code 

### PR DESCRIPTION
**Pull request by TieSKey**
Nahuel here.

Check commit comments.

Btw, Pycharm is a really good ide for python and it is free for students.

### CODE REVIEW

**Comment by ewilkinson** [comment]
Yes we are already using Pycharm

General Comments:
1. If the only changes to the file is autoformatting, you should check that in with a separate commit with the commit message that specifies you are only fixing formatting issues. The reason is that it makes it easier to know what changes are actual changes and what is just making things pretty.

2. Git ignore additions were good.

3. So, configurations involving the file directories were already being stored in the utils.py file. Moving configurations to xml is probably a good idea for big projects but if you are going to implement it you will need to implement it at 100% before I can merge it in. That means all configurations will need to be in the xml document, including all directories, feature layer names, etc (basically whats in utils). Nobody wants to be looking for configuration options in two different places. Furthermore, all existing files would need to be updated and then tested. 

Another issue that comes in with using XML is that you have to access the attributes with a string. This is not a good idea, because the IDE has no way of checking if the string you entered was valid or not. For example, 

config.db('hosts') 

will result in an error, but is not immediately obvious just by looking at it. I don't want to have a program crash after 3 hours of running because of a typo. Furthermore, there is no way for the IDE to tell me what my options are, I have to read the XML document myself to know what to input. Therefore, if you are going to implement an XML reader you need to access it like the following

config.db(config.types.HOST)

so that I can rely on the IDE to make sure I didn't have a typo. 

Conclusion
If you resubmit 21ba329 as a separate item by itself I would accept. 
If you address my points in 3 I would accept cc55960. If you decide its not worth the extra work to implement 3 then that's fine too.

**Comment by ewilkinson** [comment]
Another point about the xml. You shouldn't have seperate config/user directories you should just have a single config directory that loads a single xml file. The reason is that if you wanted to update the xml file with say a new attribute, you would need to change it in N places where N is the number of users. That doesn't make sense. Furthermore, there should be no reason to check in the XML config file unless there was an attribute change which means it will be rare. Lastly, I do not want store my username / password in plain text on a public repository.

**Comment by TieSKey** [comment]
Lets see:
1. Agreed, I messed up with the commits :s
2. No comments.
3. 
Let me explain my reasoning:
Almost all files are currently declaring local or absolute paths.
-store_feature_into_db.py
-caffe_test.py
-utils.py
-generate_features.py

Most of them are the same values but others don't. If u want to centralize all of that in utils.py that's the best approach but right now that is not complete and all the absolute paths are still there. 

I agree retrieving values from files using string keys is not elegant and can be easily improved as you mentioned. The reason to have multiple configs was to respect the absolute paths in the code that I can't be sure if u want to use or not. Db credentials are currently being stored in the code, what's the diff from putting them in a xml or whatever other plain text file? :S 
The work is not complete because I didn't want to change all what you have right now but instead let you review the idea first. I changed only 2 o 3 lines on the beginning of some files precisely to make them easy to spot and make sure any failure would be immediate.

Conclusion:
If you visualize the project structure as completely self contained then ignore the push and I'll wait until you end to materialize that structure. No harm done since that few lines of code took just a couple minutes.

Plz remember we are on the same side. I think you could have invested a lot less lines of text into explaining me the planned project structure, that you wanted to centralize paths on utils.py, that the whole thing can be self contained and doesn't need to have external user/machine dependent references, and I would have understood the changes made little sense.

**Comment by ewilkinson** [comment]
I know that Takeshi checked in his credentials, which if he wants to do is up to him. However, my comment mainly addressed the issue of having multiple xml config files, one per person. I'm not saying that the way the code is right now is better, just explaining the issues with the proposed commit.

 Just as an FYI, test files are just scripts with code that tests functionality. It isn't important to keep them up to date. 

The point of comment 3 was to explain the challenges that needed to be overcome before I could accept a change involving storing parameters in XML/yaml/JSON. I have no problem with storing params in this format, it really doesn't matter to me, its just a lot of extra work to implement. Its a a good idea, just needs to be 100% implemented before I can accept the change.

**Pull request closed without merging**
